"""Integration tests of pymend app."""

import os
import re
import subprocess
import tempfile
import textwrap
from dataclasses import asdict
from pathlib import Path
from re import Pattern

import pytest
from _pytest.mark import ParameterSet

import pymend.pymend
from pymend.const import ForceOption, OutputMode, RaisesForceMode
from pymend.pymendapp import STRING_TO_STYLE

from .util import remove_diff_header


def _params(
    mode: str = "write",
    input_style: str = "google",
    force_docstrings: str = "true",
    force_raises: str = "off",
    force_arg_types: str = "force",
) -> ParameterSet:
    return pytest.param(
        mode, input_style, force_docstrings, force_raises, force_arg_types
    )


class TestApp:
    """Test pymend as an app in a shell.

    It's an integration test.
    """

    def setup_class(self) -> None:
        """Set up class by defining docstrings."""
        # You have to run this as a module when testing so the relative imports work.
        self.CMD_PREFIX = "pymend {}"

        self.RE_TYPE = type(re.compile("get the type to test if an argument is an re"))

        # cwd to use when running subprocess.
        # It has to be at the repo directory so python -m can be used
        self.CWD = Path(__file__).parent.parent.parent

        self.INPUT = textwrap.dedent(
            '''

            def func():
                """First line

                :returns: smthg

                :rtype: ret type

                """
                pass
        '''
        )

        self.EXPECTED_OUTPUT = textwrap.dedent(
            '''\
            """_summary_."""

            def func():
                """First line.

                Returns
                -------
                ret type
                    smthg
                """
                pass
        '''
        )

        self.FILE_NO_ISSUES = textwrap.dedent(
            '''\
            """Module description."""

            def func():
                """First line.

                Returns
                -------
                ret type
                    smthg
                """
                pass
        '''
        )

        self.PATCH_PREFIX = f"# Patch generated by Pymend v{pymend.pymend.__version__}"

        # a/- and b/- is replaced by a filename when not testing stdin/stdout
        self.EXPECTED_PATCH = textwrap.dedent(
            f'''\
            {self.PATCH_PREFIX}

            --- a/-
            +++ b/-
            @@ -1,11 +1,12 @@
            +"""_summary_."""

             def func():
            -    """First line
            +    """First line.

            -    :returns: smthg
            -
            -    :rtype: ret type
            -
            +    Returns
            +    -------
            +    ret type
            +        smthg
                 """
                 pass

        '''
        )

    @classmethod
    def normalise_empty_lines(cls, lines: str) -> str:
        r"""Replace any lines that are only whitespace with a single '\n'.

        textwrap.dedent removes all whitespace characters
        on lines only containing whitespaces
        see: https://bugs.python.org/issue30754

        And some people set their editors to strip trailing white space.

        But sometimes there is a space on an empty line in the
        output which will fail the comparison.

        So strip the spaces on empty lines

        Parameters
        ----------
        lines : str
            string of lines to normalise

        Returns
        -------
        str
            normalised lines
        """
        return re.sub(r"^\s+$", "", lines, flags=re.MULTILINE)

    def run_command(
        self, cmd_to_run: str, write_to_stdin: str | None = None
    ) -> tuple[str, str, int]:
        r"""Run a command in shell mode returning stdout, stderr and the returncode.

        Parameters
        ----------
        cmd_to_run : str
            shell command to run
        write_to_stdin : str | None
            string to put on stdin if not None (Default value = None)

        Returns
        -------
        tuple[str, str, int]
            stdout, stderr, returncode
        """
        process = subprocess.Popen(  # noqa: S602
            cmd_to_run,
            shell=True,
            cwd=self.CWD,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        if write_to_stdin:
            # Python3 compatibility - input has to be bytes
            write_to_stdin = write_to_stdin.encode()
        stdout, stderr = process.communicate(write_to_stdin)

        stdout = stdout.decode()
        stderr = stderr.decode()
        return stdout, stderr, process.returncode

    def assert_output(
        self,
        cmd_to_run: str,
        what: str,
        got: str | int,
        expected: str | Pattern[str] | int,
        *,
        invert: bool,
    ) -> None:
        """See run_pymend_app_and_assert_is_expected.

        Parameters
        ----------
        cmd_to_run : str
            full command that was run - used to build an error message
        what : str
            The attribute being checked - used for the error message
        got : str
            The result from the test
        expected : Union[str, Pattern[str]]
            The expected result from the test
        invert: bool
            Whether to assert that got does not match expected

        Raises
        ------
        AssertionError
            If the expected result is not found
        """
        if isinstance(expected, self.RE_TYPE) and isinstance(got, str):
            msg = (
                f"Test failed for cmd {cmd_to_run}\n{what} was "
                f"{'not ' if invert else ''}expected to match the regex:\n"
                f"{expected}\n"
                f"But this was the output:\n{got!r}\n"
            )

            if invert:
                assert expected.search(got) is None, msg
            else:
                assert expected.search(got) is not None, msg
        else:
            if isinstance(expected, str) and isinstance(got, str):
                # Turn lines that only have whitespace into
                # single newline lines to workaround textwrap.dedent
                # behaviour
                got = remove_diff_header(
                    self.normalise_empty_lines(got).replace("\r\n", "\n")
                )
                expected = remove_diff_header(self.normalise_empty_lines(expected))

            msg = (
                f"Test failed for cmd {cmd_to_run}\n{what} was "
                f"{'not ' if invert else ''}expected to be:"
                f"\n{expected!r}\nBut this was the output:\n{got!r}\n"
            )

            if invert:
                assert got != expected, msg
            else:
                assert got == expected, msg

    def run_pymend_app_and_assert_is_expected(
        self,
        cmd_args: str,
        write_to_stdin: str | None = None,
        expected_stdout: str | Pattern[str] = "",
        expected_stderr: str | Pattern[str] = "",
        expected_returncode: int = 0,
        *,
        invert_stderr: bool = False,
        invert_stdout: bool = False,
        invert_returncode: bool = False,
    ) -> None:
        """Run pymend and assert it's output matches the arguments.

        With the cmd_args and output_format specified in a shell.

        If expected_stdout and expected_stderr is the result of a re.compile()
        the output will be checked with re.search().

        Parameters
        ----------
        cmd_args : str
            Extra arguments to pass to pymend - excluding the output_format
        write_to_stdin : Optional[str]
            The input to put on stdin,
            use None if there's nothing (Default value = None)
        expected_stdout : str | Pattern[str]
            Expected string to see on stdout (Default value = "")
        expected_stderr : str | Pattern[str]
            Expected string to see on stderr (Default value = "")
        expected_returncode : int
            Expected returncode after running pymend (Default value = 0)

        Raises
        ------
        AssertionError
            If the expected result is not found
        """
        cmd_to_run = self.CMD_PREFIX.format(cmd_args)

        stdout, stderr, returncode = self.run_command(cmd_to_run, write_to_stdin)
        self.assert_output(
            cmd_to_run, "stderr", stderr, expected_stderr, invert=invert_stderr
        )
        self.assert_output(
            cmd_to_run, "stdout", stdout, expected_stdout, invert=invert_stdout
        )
        self.assert_output(
            cmd_to_run,
            "returncode",
            returncode,
            expected_returncode,
            invert=invert_returncode,
        )

    def test_no_args_ge_py33(self) -> None:
        """Ensure the app outputs an error if there are no arguments."""
        self.run_pymend_app_and_assert_is_expected(
            cmd_args="",
            write_to_stdin=None,
            expected_stderr=re.compile(
                r"Usage: pymend \[OPTIONS\] SRC \.\.\..*"
                r"Error: Missing argument 'SRC \.\.\.'\.",
                re.DOTALL,
            ),
            expected_returncode=1,
        )

    @pytest.mark.parametrize(
        ("mode", "input_style", "force_docstrings", "force_raises", "force_arg_types"),
        [
            *(_params(mode=str(mode)) for mode in OutputMode),
            *(
                _params(input_style=str(input_style))
                for input_style in (*STRING_TO_STYLE, "auto")
            ),
            *(
                _params(force_docstrings=force_docstrings)
                for force_docstrings in ("true", "false")
            ),
            *(
                _params(force_raises=f'"{force_raises}"')
                for force_raises in RaisesForceMode
            ),
            *(
                _params(force_raises=str(force_raises))
                for force_raises in ("true", "false")
            ),
            *(
                _params(force_arg_types=str(force_arg_types))
                for force_arg_types in ForceOption
            ),
        ],
    )
    def test_valid_pyproject_passes(
        self,
        tmp_path: Path,
        mode: str,
        input_style: str,
        force_docstrings: str,
        force_raises: str,
        force_arg_types: str,
    ) -> None:
        """Test that the valid options in pyproject succeed."""
        pyproject_content = textwrap.dedent(f"""\
            [tool.pymend]
            mode = "{mode}"
            output-style = "numpydoc"
            input-style = "{input_style}"
            exclude = "docs/|tests/"
            extend-exclude = "build/"
            force-docstrings = {force_docstrings}
            force-params = true
            force-return = true
            force-raises = {force_raises}
            force-methods = false
            force-attributes = false
            force-params-min-n-params = 0
            force-meta-min-func-length = 0
            ignore-privates = true
            ignore-unused-arguments = true
            ignored-decorators = ["overload"]
            ignored-functions = ["main"]
            ignored-classes = []
            force-defaults = true
            force-return-type = "force"
            force-arg-types = "{force_arg_types}"
            force-attribute-types = "force"
            force-summary-period = true
            force-summary-blank-line = true
            force-multiline-docs-end-with-blank = false
            indent = 4
            attribute-class-decorators = ["dataclass"]
            attribute-base-classes = ["BaseModel"]
            property-decorators = ["property"]
            additional-excluded-decorators = ["staticmethod", "classmethod"]
        """)

        n_options = len([line for line in pyproject_content.split("\n") if "=" in line])
        n_non_fixer_options = len(
            ["mode", "output-style", "input-style", "exclude", "extend-exclude"]
        )
        assert (
            n_options
            == len(asdict(pymend.pymend.FixerSettings())) + n_non_fixer_options
        )

        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(pyproject_content)

        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(
                f"--config {pyproject_file} --check-only "
                f"{self.CWD}/src/pymend/pymend.py"
            ),
            expected_stderr=re.compile(
                r"Usage: pymend.*Error",
                re.DOTALL,
            ),
            expected_stdout="Doesnt matter",
            expected_returncode=2,
            invert_stderr=True,
            invert_stdout=True,
            invert_returncode=True,
        )

    def test_invalid_value_type_pyproject_options_raises(self, tmp_path: Path) -> None:
        """Test that a valid option but with invalid type in pyproject fails."""
        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(
            textwrap.dedent("""\
            [tool.pymend]
            force-docstrings = '5'
        """)
        )

        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(f"--config {pyproject_file} {self.CWD}/src/pymend/pymend.py"),
            expected_stderr=re.compile(
                r"Usage: pymend \[OPTIONS\] SRC \.\.\..*"
                r"Error: Invalid value for '--force-docstrings': '5'",
                re.DOTALL,
            ),
            expected_returncode=2,
        )

    def test_invalid_pyproject_option_raises(self, tmp_path: Path) -> None:
        """Test that a pyproject.toml file with an invalid option reports an error."""
        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(
            textwrap.dedent("""\
            [tool.pymend]
            invalid-option = '5'
        """)
        )

        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(f"--config {pyproject_file} {self.CWD}/src/pymend/pymend.py"),
            expected_stderr=re.compile(
                r"Usage: pymend \[OPTIONS\] SRC \.\.\..*"
                r"Error: Found unknown option in pyproject.toml: *",
                re.DOTALL,
            ),
            expected_returncode=2,
        )

    def test_invalid_pyproject_options_raises(self, tmp_path: Path) -> None:
        """Test that a pyproject file with multiple invalid options raises an error."""
        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(
            textwrap.dedent("""\
            [tool.pymend]
            invalid-option = '5'
            other-invalid-option = true
        """)
        )

        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(f"--config {pyproject_file} {self.CWD}/src/pymend/pymend.py"),
            expected_stderr=re.compile(
                r"Usage: pymend \[OPTIONS\] SRC \.\.\..*"
                "Error: Found unknown options in pyproject.toml:"
                r" `invalid-option`, `other-invalid-option`\.",
                re.DOTALL,
            ),
            expected_returncode=2,
        )

    @pytest.mark.parametrize(
        "option",
        [
            "diff",
            "write",
            "check-only",
            "verbose",
            "quiet",
            "src",
            "noforce-arg-types",
            "unforce-arg-types",
            "noforce-return-type",
            "unforce-return-type",
            "noforce-attribute-types",
            "unforce-attribute-types",
            "noforce-raises",
            "force-raises-per-type",
        ],
    )
    def test_cli_only_option_rejected_in_pyproject(
        self, tmp_path: Path, option: str
    ) -> None:
        """Test that CLI-only options are not accepted in pyproject.toml."""
        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(
            textwrap.dedent(f"""\
            [tool.pymend]
            {option} = true
        """)
        )

        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(f"--config {pyproject_file} {self.CWD}/src/pymend/pymend.py"),
            expected_stderr=re.compile(
                r"Usage: pymend \[OPTIONS\] SRC \.\.\..*"
                r"Error: Found unknown option in pyproject.toml: *",
                re.DOTALL,
            ),
            expected_returncode=2,
        )

    @pytest.mark.parametrize(
        "pyproject_content",
        [
            pytest.param('tool = "stuff"', id="tool-is-string"),
            pytest.param(
                textwrap.dedent("""\
                [tool]
                pymend = "stuff"
            """),
                id="pymend-is-string",
            ),
        ],
    )
    def test_non_table_tool_or_pymend_ignored(
        self, tmp_path: Path, pyproject_content: str
    ) -> None:
        """Non-dict tool or pymend entries are treated as missing config."""
        pyproject_file = tmp_path / "pyproject.toml"
        pyproject_file.write_text(pyproject_content)
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=(f"--config {pyproject_file} {self.CWD}/src/pymend/pymend.py"),
            expected_stderr=re.compile("All done!"),
        )

    def run_pymend_app_with_a_file_and_assert_is_expected(
        self,
        file_contents: str,
        cmd_args: str = "",
        *,
        overwrite_mode: bool = False,
        expected_file_contents: str | Pattern[str] = "",
        expected_stderr: str | Pattern[str] = "",
        expected_stdout: str | Pattern[str] = "",
        expected_returncode: int = 0,
    ) -> None:
        """
        Run the pymend app with a file - not stdin.

        A temporary file is created,
        file_contents is written into it then the test is run.
        The .patch and temporary files are removed at the end of the test.

        Parameters
        ----------
        file_contents : str
            write this into the temporary file
        cmd_args : str
            Arguments to pymend - do not put the '--write' argument here -
            it is triggered by overwrite_mode (Default value = "")
        overwrite_mode : bool
            set to True if in overwrite mode (Default value = False)
        expected_file_contents : str | Pattern[str]
            expected result - for a patch file ensure the filename is '-'.
            The '-' (Default value = "")
        expected_stderr : str | Pattern[str]
            expected output on stderr.
            You can match on a regex if you pass it the result of (Default value = "")
        expected_stdout : str | Pattern[str]
            Expected string to see on stdout (Default value = "")
        expected_returncode : int
            Expected return code from pymend. Default is 0.
        output_format : Optional[str]
            If not using auto mode set the output format to this. (Default value = None)
        """
        patch_filename = Path()
        input_filename = ""
        input_file = None

        try:
            # Create the input file
            input_fd, input_filename = tempfile.mkstemp(suffix=".input", text=True)
            input_file = os.fdopen(input_fd, "w")
            input_file.write(file_contents)
            input_file.close()

            # Get the patch file name so it can be removed if it's created.
            # pymend will create it in the current working directory
            patch_filename = self.CWD / Path(f"{Path(input_filename).name}.patch")

            cmd_args = f"{cmd_args} {input_filename}"

            if overwrite_mode:
                cmd_args = f"{cmd_args} --write "

            self.run_pymend_app_and_assert_is_expected(
                cmd_args=cmd_args,
                expected_stderr=expected_stderr,
                expected_returncode=expected_returncode,
                expected_stdout=expected_stdout,
                write_to_stdin=file_contents,
            )

            if overwrite_mode:
                with Path(input_filename).open(encoding="utf-8") as file:
                    output = file.read()
            else:
                with patch_filename.open(encoding="utf-8") as file:
                    output = file.read()
                # The expected output will have filenames of '-'
                # - replace them with the actual filename
                output = re.sub(
                    rf"/{Path(input_filename).name}$",
                    r"/-",
                    output,
                    flags=re.MULTILINE,
                )

            normalised_output = self.normalise_empty_lines(output)
            normalised_expected_output = self.normalise_empty_lines(
                expected_file_contents
            )
            assert remove_diff_header(normalised_output) == remove_diff_header(
                normalised_expected_output
            ), (
                f"Output from cmd: {cmd_args} was:\n{normalised_output!r}\nnot "
                f"the expected:\n{normalised_expected_output!r}"
            )

        finally:
            if input_filename:
                if input_file and not input_file.closed:
                    input_file.close()
                Path(input_filename).unlink()

            if not overwrite_mode and patch_filename.is_file():
                patch_filename.unlink()

    def test_overwrite_files_the_same_with_defaults(self) -> None:
        """Test that file with defaults has issues even without changes."""
        self.run_pymend_app_with_a_file_and_assert_is_expected(
            file_contents=self.EXPECTED_OUTPUT,
            expected_stderr=re.compile("Oh no! .*"),
            expected_file_contents=self.EXPECTED_OUTPUT,
            overwrite_mode=True,
            expected_returncode=1,
        )

    def test_overwrite_files_the_same_no_defaults(self) -> None:
        """Test that file without defaults and no changes returns 0."""
        self.run_pymend_app_with_a_file_and_assert_is_expected(
            file_contents=self.FILE_NO_ISSUES,
            expected_stderr=re.compile("All done! .*"),
            expected_file_contents=self.FILE_NO_ISSUES,
            overwrite_mode=True,
        )

    def test_overwrite_files_different(self) -> None:
        """Test the file is overwritten with the correct result."""
        self.run_pymend_app_with_a_file_and_assert_is_expected(
            file_contents=self.INPUT,
            expected_file_contents=self.EXPECTED_OUTPUT,
            expected_stderr=re.compile("Oh no! .*"),
            expected_stdout=re.compile(
                r"Modified docstrings of elements \(Module, func\) in file.*", re.DOTALL
            ),
            overwrite_mode=True,
            expected_returncode=1,
        )

    def test_patch_files_the_same_with_defaults(self) -> None:
        """Check patch file when files are the same but have defaults."""
        with pytest.raises(FileNotFoundError):
            self.run_pymend_app_with_a_file_and_assert_is_expected(
                file_contents=self.EXPECTED_OUTPUT,
                expected_stderr=re.compile("Oh no! .*"),
                expected_file_contents=self.PATCH_PREFIX + "\n",
                expected_returncode=1,
            )

    def test_patch_files_the_same_no_defaults(self) -> None:
        """Check patch file when files are the same without defaults."""
        with pytest.raises(FileNotFoundError):
            self.run_pymend_app_with_a_file_and_assert_is_expected(
                file_contents=self.FILE_NO_ISSUES,
                expected_stderr=re.compile("All done! .*"),
                expected_file_contents=self.PATCH_PREFIX + "\n",
            )

    def test_patch_files_different(self) -> None:
        """Test the patch file is correct."""
        self.run_pymend_app_with_a_file_and_assert_is_expected(
            file_contents=self.INPUT,
            expected_stderr=re.compile("Oh no! .*"),
            expected_file_contents=self.EXPECTED_PATCH,
            expected_returncode=1,
        )

    def test_numpy_unforce_return_type_rejected(self) -> None:
        """Using --unforce-return-type with NumPy output style is rejected."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"{src} --output-style=numpydoc --unforce-return-type",
            expected_stderr=re.compile(
                r"Error: NumPy docstring style requires return types"
            ),
            expected_returncode=2,
        )

    def test_mode_mutually_exclusive(self) -> None:
        """Passing --diff and --write together is rejected."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"--diff --write {src}",
            expected_stderr=re.compile(r"Mutually exclusive"),
            expected_returncode=2,
        )

    def test_force_arg_types_mutually_exclusive(self) -> None:
        """Passing --force-arg-types and --noforce-arg-types together is rejected."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"--force-arg-types --noforce-arg-types {src}",
            expected_stderr=re.compile(r"Mutually exclusive"),
            expected_returncode=2,
        )

    def test_force_return_type_mutually_exclusive(self) -> None:
        """Conflicting --force/--unforce-return-type flags are rejected."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"--force-return-type --unforce-return-type {src}",
            expected_stderr=re.compile(r"Mutually exclusive"),
            expected_returncode=2,
        )

    def test_force_attribute_types_mutually_exclusive(self) -> None:
        """Passing conflicting --force/--noforce-attribute-types is rejected."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"--force-attribute-types --noforce-attribute-types {src}",
            expected_stderr=re.compile(r"Mutually exclusive"),
            expected_returncode=2,
        )

    def test_mode_all_three_reported(self) -> None:
        """Passing all three mode flags lists every conflicting flag."""
        src = Path(__file__).parent / "refs" / "issue30.py"
        self.run_pymend_app_and_assert_is_expected(
            cmd_args=f"--diff --write --check-only {src}",
            expected_stderr=re.compile(r"`--check-only`, `--diff`, `--write`"),
            expected_returncode=2,
        )

    def test_option_group_ordering_valid(self) -> None:
        """Importing pymendapp succeeds — group options are correctly ordered."""
        from pymend import pymendapp  # noqa: F401, PLC0415
